/**
 * CREDShield Contract — Barrel Export
 *
 * Exports the compiled contract artifacts, witness providers, and types
 * for use by the frontend and tests.
 */

export * from "./witnesses.js";

// Re-export the compiled contract module (generated by `compact compile`).
// Run `npm run compact` to generate the managed/ directory.
// The export below is commented out until the Compact compiler generates the artifacts.
// Uncomment after running: npm run compact
//
// export { Contract } from "./managed/credshield/contract/index.cjs";
